name: Fluent Bit build with disk plugin

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build --build-arg VERSION=3.1.4 --tag fluent-bit:3.1.4-with-disk .
